[package]
name = "podnet-models"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
pod2.workspace = true
pod-utils = { path = "../utils" }

[dev-dependencies]
tokio = { version = "1.0", features = ["rt", "macros"] }
